{{- if .Values.followChangesForBranch }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-source
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
{{- end }}