{{- if .Values.followChangesForBranch }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: build-cache-pvc
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
{{- end }}