{{- if .Values.followChangesForBranch }}
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: wind-turbine-pipeline
spec:
  params:
  - name: GIT_REVISION
    type: string
  - default: {{ coalesce .Values.applicationGitUrl "https://github.com/gmodzelewski/nodejsdockerpipeline.git" }}
    name: GIT_REPO
    type: string
  - default: "empty"
    name: GIT_COMMIT_MESSAGE
    type: string
  - default: {{ coalesce .Values.imageTag "latest" }}
    name: IMAGE_TAG
    type: string
  - default: {{ coalesce .Values.image "quay.io/modzelewski/nodejsdockerpipeline" }}
    name: IMAGE_NAME
    type: string
  tasks:
  - name: git-clone
    params:
    - name: url
      value: $(params.GIT_REPO)
    - name: revision
      value: $(params.GIT_REVISION)
    - name: submodules
      value: "true"
    - name: depth
      value: "1"
    - name: sslVerify
      value: "true"
    - name: crtFileName
      value: ca-bundle.crt
    - name: deleteExisting
      value: "true"
    - name: verbose
      value: "true"
    - name: gitInitImage
      value: registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:cadf614a6044ee37397de3abe7674827ecab225e7fac9fb123eff5473e2c4003
    - name: userHome
      value: /tekton/home
    taskRef:
      kind: ClusterTask
      name: git-clone
    workspaces:
    - name: output
      workspace: source
  - name: maven
    params:
    - name: MAVEN_IMAGE
      value: quay.io/rhdevelopers/maven-nodejs:latest
    - name: GOALS
      value:
      - package
    - name: PROXY_PROTOCOL
      value: http
    - name: CONTEXT_DIR
      value: .
    runAfter:
    - git-clone
    taskRef:
      kind: ClusterTask
      name: maven
    workspaces:
    - name: maven-settings
      workspace: maven-settings
    - name: source
      workspace: source
  - name: buildah
    params:
    - name: IMAGE
      value: $(params.IMAGE_NAME):$(params.IMAGE_TAG)
    - name: BUILDER_IMAGE
      value: registry.redhat.io/rhel8/buildah@sha256:0a86ecbdfbe86e9d225b7fe4b090a0dd6d323f8afdfdf2bd933ff223ddb53320
    - name: STORAGE_DRIVER
      value: vfs
    - name: DOCKERFILE
      value: {{ coalesce .Values.containerfilepath './client/Dockerfile' }}
    - name: CONTEXT
      value: .
    - name: TLSVERIFY
      value: "true"
    - name: FORMAT
      value: oci
    - name: SKIP_PUSH
      value: "false"
    runAfter:
    - maven
    taskRef:
      kind: ClusterTask
      name: buildah
    workspaces:
    - name: source
      workspace: source
  workspaces:
  - name: source
  - name: maven-settings
{{- end }}