{{- if .Values.followChangesForBranch }}
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: wind-turbine
spec:
  params:
    - name: content-type
      value: $(header.Content-Type)
    - name: git-commit-message
      value: $(body.head_commit.message)    
    - name: git-repo-name
      value: $(body.repository.name)
    - name: git-repo-url
      value: $(body.repository.url)
    - name: git-revision
      value: $(body.head_commit.id)
    - name: pusher-name
      value: $(body.pusher.name)
{{- end }}