manifestsGitUrl: 'https://github.com/gmodzelewski/nodejsDockerPipeline'
# manifestsGitBranch: main
applicationGitUrl: 'https://github.com/ABPozharliev19/sparely'
image: 'quay.io/modzelewski/nodejsdockerpipeline'
imageTag: latest # Overwrite this value in the applicationSet - wind-turbine-app.yaml
followChangesForBranch: main # default: empty -> if set, tekton files get created
stage: dev # must be the name of the stage folder with the config.json
containerfilepath: './client/Dockerfile'